---
title: "analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source('./src/install_needed_packages.R')

pack.ls <- c('rstan','parallel','readr','magrittr','dplyr','tidybayes','ggplot2', 'modelr','tidyr','forcats','cowplot','bayesplot','huxtable','officer','flextable', 'lme4')

## load in packages without messages
for (package in pack.ls){
    suppressPackageStartupMessages(
        library(package,
                character.only=TRUE))
}
```

```{r}
dat <- read.csv('./dat/cleaned/titer_data.csv')
```

Fit the model
```{r}

source('./src/fit_stan_model.R')
model_src_path <- './src/titer_decay_model.stan'
  
fit <- stan(
    model_src_path,
    data = stan_data,
    iter = niter,
    seed = fixed_seed,
    chains = nchains,
    init = init_val,
    control = list(max_treedepth = max_tree,
                   adapt_delta = adapt_d))

cat('\nsaving mcmc samples to', mcmc_output_path, '\n')

saveRDS(fit, './out/mcmc_fit.rds')

```

Chain diagnostics

```{r}

source('./src/chain_diagnostics.R')

```
Plotting
```{r}
source('./src/plotting_style.R')
```

Test out some different approach

```{r}
d1 <- dat[dat$virus=='HCoV-19' & dat$log10_titer>dat$detection_limit_log10_titer,] #SARS-CoV2 and exclude negative

d1$titer <- 10^d1$log10_titer

d1 <- d1 %>%
  group_by(material, humidity, temperature, replicate) %>%
  mutate(unique_replicate= cur_group_id())

mod1 <- lmer(log10_titer ~ 0 +material + time + material*time +  (time|unique_replicate), data=d1)

 
#log10((10^log10_conc_0)/2) = log10_conc_0 - lambda*t
#t_half=  (log10_conc_0 -log10((10^log10_conc_0)/2) )/lambda

t_half_aero <- (2.7 - log10((10^2.7)/2 ))/0.24425

t_half_card <- (2.54 - log10((10^2.54)/2 ))/(0.24425-0.177331)
t_half_copper <- (3.05 - log10((10^3.05)/2 ))/(0.2444- -0.04557)
t_half_steel <- (2.09 - log10((10^2.09)/2 ))/(0.2444-0.2393)



 summary(lm(log10_titer ~ 0 +material + time + material*time, data=d1))

```




